"""add clients table

Revision ID: 360436adbe93
Revises: 5b097fe4d9ff
Create Date: 2020-04-19 20:17:40.578142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360436adbe93'
down_revision = '5b097fe4d9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fio', sa.String(length=90), nullable=True),
    sa.Column('tovar', sa.String(length=140), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=140), nullable=True),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'price', 'cost_price', 'profit')
    )
    op.create_index(op.f('ix_client_timestamp'), 'client', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_timestamp'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
