"""leads table

Revision ID: 75d92a19e35b
Revises: e7a29600decc
Create Date: 2020-04-23 13:06:06.018704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d92a19e35b'
down_revision = 'e7a29600decc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fio', sa.String(length=90), nullable=True),
    sa.Column('tovar', sa.String(length=140), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=140), nullable=True),
    sa.Column('cost_price', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Integer(), nullable=True),
    sa.Column('track', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index('ix_client_timestamp')

    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('fio', sa.VARCHAR(length=90), nullable=True),
    sa.Column('tovar', sa.VARCHAR(length=140), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=140), nullable=True),
    sa.Column('cost_price', sa.INTEGER(), nullable=False),
    sa.Column('profit', sa.INTEGER(), nullable=False),
    sa.Column('track', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'price', 'cost_price', 'profit')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index('ix_client_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_timestamp'))

    op.drop_table('lead')
    # ### end Alembic commands ###
