"""ch tovars table

Revision ID: 856b26cc292b
Revises: b8e5cceaf7b2
Create Date: 2020-05-01 19:35:03.682550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856b26cc292b'
down_revision = 'b8e5cceaf7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('delivery_price')

    # ### end Alembic commands ###
