"""tovars table

Revision ID: b8e5cceaf7b2
Revises: 367d5224e02e
Create Date: 2020-05-01 18:30:03.396641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e5cceaf7b2'
down_revision = '367d5224e02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tovar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tovar_name', sa.String(length=140), nullable=True),
    sa.Column('tovar_cost_price', sa.Float(), nullable=True),
    sa.Column('tovar_price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BIK', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('INN', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('KPP', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comp_bill', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comp_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('cor_bill', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_delivery', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('default_delivery')
        batch_op.drop_column('cor_bill')
        batch_op.drop_column('comp_name')
        batch_op.drop_column('comp_bill')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('KPP')
        batch_op.drop_column('INN')
        batch_op.drop_column('BIK')

    op.drop_table('tovar')
    # ### end Alembic commands ###
